### ISSUE TITLE
Needs to be updated to work with Joomla 3

### ISSUE THREAD

**Issue by harmlessdrudge** [ruflin/DokuWiki-Joomla-Bridge#1]
This code provided single sign-on to **Joomla** and **DokuWiki** using the same MySQL database.

It was superceded by [jfusion](https://github.com/jfusion) which provided bridge functionality for a range of applications -- phpBB, [DokuWiki](https://www.dokuwiki.org), MyBB, Magento and others -- up to Joomla 2.5.

Jfusion3, intended to work with Joomla v3, has apparently been abandoned after a long period in beta (one developer with other priorities). A support site, jfusion.org, has disappeared recently. (See [Internet Archive](https://web.archive.org/web/20161024022925/http://www.jfusion.org/)

There is currently no extension in the [Joomla extensions directory](https://extensions.joomla.org/) to provide the required functionality for the current versions of Joomla and DokuWiki but the requirement for one surfaces regularly as a topic on the [DokuWiki forum](https://forum.dokuwiki.org/forum.php?req=search&Query=joomla&ResultView=2&InSubject=1&InMessage=1&Sort=2&DateFrom=&DateUntil=&Forum=0)

See [message](https://forum.dokuwiki.org/post/55078;nocount) in the DokuWiki forum about a [Bountysource](https://www.bountysource.com) bounty for resolving this issue. Funded with an initial $50. Additional contributions welcome.

**Comment by snaiperskaya96** [comment]
Hello, I've extended the authpdo plugin and made another plugin called authjoomla3.
It will handle authentication against Joomla by just specifying the joomla (absolute) path inside DokuWiki config.
This is the repository of the plugin https://github.com/snaiperskaya96/dokuwiki-authjoomla3-plugin .
To make it work:
  - Download the source from github
  - Create a folder inside dokuwiki/lib/plugins called authjoomla3
  - Navigate to your doku wiki config page (doku.php?id=start&do=admin&page=config)
  - The first thing to do is to go to the Authentication page and change `Authentication backend` with authjoomla3. Do not save yet.
  - Scroll down to the last row and you should see `plugin authjoomla3 joomlaPath` there you have to specify a valid joomla3 installation path
  - Save and everything should work.

Now a few notes:

  - Since we're using joomla users and group, I left the management to joomla itself, so you cannot add/delete/update users or groups from dokuwiki but instead you want to do it from joomla.
  - Joomla's `Super Users` and `Administrator` group are locally renamed (means it happens only on dokuwiki) to `admin` in order to make them administrator on DokuWiki without any other change.

Let me know!

**Comment by harmlessdrudge** [comment]
Thanks for your quick response on this. I'll try it over the weekend. I've commented on the DokuWiki forum.

**Comment by ruflin** [comment]
As you can probably see from the source code, I didn't touch it for about 6 years (time is flying). I'm happy to accept PR's to make it working again or also happy if someone wants to use this in a fork. But I currently do not plan to push this forward myself.

**Comment by harmlessdrudge** [comment]
Can you close the open issue? This will make the bounty payable without any hassle (not sure how necessary it is but for sure it will not be a problem if the issue is closed). We can decide on a fork later if needed. Thanks, also for your earlier efforts on this.

**Comment by ruflin** [comment]
Sure, just closed the issue.
